name: Javadoc

on:
  # after a push to master ora successful pull request
  push:
    branches:
      - master

jobs:
  deploy-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64

      - name: Compile Javadoc
        run: >
          mvn javadoc:javadoc ;
          mkdir out;
          mv target/site/apidocs out/javadoc


      - name: Deploy to gh-pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: out
          GITHUB_TOKEN: ${{ secrets.CREMA_TOKEN }}
          MESSAGE: "Update with commit {sha}:\n{msg}"
          CLEAR_GLOBS_FILE: ".clear-target-files"
