name: GitHub Pages Deploy Action for Javadoc

on:
  # after a push to master ora successful pull request
  push:
    branches:
      - master

jobs:
  deploy-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      # Use avinal/github-pages-deploy-action@<latest-release-tag> for latest stable release
      - uses: avinal/github-pages-deploy-action@main
        with:
          GITHUB_TOKEN: ${{ CREMA_TOKEN }}
          LANGUAGE: "java"
          # Write make command to generate html e.g.- "make html"
          MAKE_COMMAND: "make html"
          # Write the branch name for storing github pages source
          PAGES_BRANCH: "gh-pages"
          # Write the branch name having source files for site/documentation
          BUILD_FROM: "master"
          # Write the name of the output folder where generated html is stored by makefile.
          DOCS_FOLDER: "javadoc"
